project:
  type: website
  resources:
    - "posts/**/*.pmtiles"

website:
  title: "Aman Bagrecha"
  description: "Aman is a geospatial scientist at Galaxeye Space and runs a geospatial community Lets Talk Spatial"
  site-url: https://amanbagrecha.com
  draft-mode: unlinked
  favicon: img/favicon.png
  navbar:
    search: true
    tools:
      - icon: twitter
        href: https://twitter.com/aman_bagrecha
      - icon: github
        href: https://github.com/amanbagrecha
      - icon: youtube
        href: https://www.youtube.com/@amanbagrecha/videos
    pinned: true
    logo: img/ab-logo-small.png
    left:
      - text: "Home"
        file: index.qmd
      - text: Videos
        file: talks/index.qmd
      - text: Posts
        file: posts.qmd
      # - href: notebooks
      #   text: Notebooks
      - text: Events
        file: events.qmd
      - text: Travel
        file: travel/index.qmd
      - text: Projects
        file: projects.qmd
      - text: Presentations
        file: presentations/index.qmd
      - text: "Tools"
        menu:
          - text: "Photo Search"
            file: tools/photo-search.qmd
          - text: "TiTiler Viewer"
            href: tools/titiler-viewer/titiler_viewer.html
  page-footer:
    left: "Copyright Â© Aman Bagrecha, 2025. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true

format:
  html:
    theme:
      # - sandstone
      - custom.scss
    page-layout: article
    css: styles.css
    # grid:
    #   body-width: 150px
    toc: true
    fontsize: 1.1em
    linestretch: 1.8
    fontcolor: black

    # linkcolor: hsl(210deg 60% 40%)

# spacelab, superhero, simplex, sandstone, flatly

